version: 2
jobs:
  recovery-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: generate config
          command: |
            cat > appconfig.json <<EOF
            {
              "MINIFY": true,
              "NETWORK": "BCH",
              "NETWORK_LONG": "Bitcoin Cash",
              "RECOVER_LITECOIN": false,
              "RECOVER_BCC": true,
              "RECOVER_BTG": false,
              "LOGIN_BASED_RECOVERY": false,
              "RECOVERY_BACKEND": "https://recovery-backend.blocktrail.com",
              "API_URL": "https://wallet-api.btc.com"
            }
            EOF

      - run: sudo npm install -g gulp@3.9.1
      - run: npm install gulp@3.9.1
      - run: npm install
      - run: gulp
      - run: sudo apt install python-pip python-dev -y;sudo pip install awscli
      - run:
          name: sync to aws
          command: |
            ## shame on you CircleCi
            AWS_ACCESS_KEY_ID=$MY_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$MY_AWS_SECRET_ACCESS_KEY aws s3 sync build s3://$RECOVERY_CDN


  bsv-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run: git checkout f/recover-sv
      - run:
          name: generate config
          command: |
            cat > appconfig.json <<EOF
            {
              "MINIFY": true,
              "NETWORK": "BSV",
              "NETWORK_LONG": "Bitcoin SV (BSV)",
              "RECOVER_LITECOIN": false,
              "RECOVER_BCC": false,
              "RECOVER_BSV": true,
              "RECOVER_BTG": false,
              "LOGIN_BASED_RECOVERY": true,
              "RECOVERY_BACKEND": "https://recovery-backend.blocktrail.com",
              "COSIGN_ENDPOINT": "signbsv",
              "API_URL": "https://wallet-api.btc.com"
            }
            EOF

      - run: sudo npm install -g gulp@3.9.1
      - run: npm install gulp@3.9.1
      - run: npm install
      - run: gulp
      - run: sudo apt install python-pip python-dev -y;sudo pip install awscli
      - run:
          name: sync to aws
          command: |
            ## shame on you CircleCi
            AWS_ACCESS_KEY_ID=$MY_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$MY_AWS_SECRET_ACCESS_KEY aws s3 sync build s3://$BSV_RECOVERY_CDN

  btg-build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: git checkout btg
      - run:
          name: generate config
          command: |
            cat > appconfig.json <<EOF
            {
                "MINIFY": true,
                "RECOVER_LITECOIN": false,
                "RECOVER_BTG": true,
                "NETWORK": "BTG",
                "NETWORK_LONG": "Bitcoin Gold",
                "LOGIN_BASED_RECOVERY": false,
                "RECOVERY_BACKEND": "https://recovery-backend.blocktrail.com",
                "API_URL": "https://wallet-api.btc.com",
                "GA_TRACKING_ID": "UA-66176065-31"
            }
            EOF

      # Download and cache dependencies
      - run: sudo npm install -g gulp@3.9.1
      - run: npm install gulp@3.9.1
      - run: npm install
      - run: gulp
      - run: sudo apt install python-pip python-dev -y;sudo pip install awscli
      - run:
          name: sync to aws
          command: |
            ## shame on you CircleCi
            AWS_ACCESS_KEY_ID=$MY_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$MY_AWS_SECRET_ACCESS_KEY aws s3 sync build s3://$BTG_RECOVERY_CDN


workflows:
  version: 2
  build-deploy:
    jobs:
      - recovery-build:
          filters:
            branches:
              only: /.*/

      - bsv-build:
          filters:
            branches:
              only: /.*/

      - btg-build:
          filters:
            branches:
              only: /.*/